### ISSUE TITLE
bbs.pyは問題ありませんが一点追加して欲しいものがあります

### ISSUE THREAD

**Issue by noboji2525** [gens-code/test_repository#1]
READ.mdファイルを作りましょう
簡単にで良いので機能説明なども載せておくこと！
また.mdファイルはマークダウンという記法を使って素早くドキュメントをきれいにしてくれますので、合わせて調べてみてください！

**Comment by gens-code** [comment]
ひとこと掲示板の説明だけ書きました！

**Comment by noboji2525** [comment]
OKですCloseお願いします
